spring.application.name=lab1

# mysql 
spring.datasource.url=jdbc:mysql://localhost:3306/entornos_lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# jpa 
#genera o actualiza tablas en la bd auto
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true
#Indica a hibernate que las consultas sql sean pretty
spring.jpa.properties.hibernate.format_sql=true